### ISSUE TITLE
Git package "Depends" field broken: comma missing

### ISSUE THREAD

**Issue by Thireus** [radare/cydia#1]
The git package in the repository contains a mistake:

    "Depends: expat cacert"

should be instead

    "Depends: expat, cacert"

As a result this is what Cydia displays:

![git newversion1 from radare repository](https://cloud.githubusercontent.com/assets/721759/21570575/22c480a4-cebf-11e6-90e9-867f4498c933.jpg)

    W: Problem parsing dependency Depends
    W: Error occurred while processing git (NewVersion1)
    W: You may want to run apt-get update to correct these problems

The issue is due to a comma that is missing in the package "Depends" field of the git version (2.11.0) of cydia.radare.org. Because of this the package cannot be processed as it should, and is failing to find the package dependencies. The git package isn't listed in the package list of the cydia.radare.org source, however it can be found in the Package.bz archive or via "apt-cache policy git" which should output the following:

      Version table:
         2.11.0 0
     *** 2.8.1-5 0

*These lines show that the version "2.8.1-5" is installed (the one from Saurik repository) and that there is a 2.11.0 version (the one from cydia.radare.org repository).*

**This warning doesn't cause any harm. It just states that the git package from "cydia.radare.org" is broken.**

**Comment by radare** [comment]
uhm https://github.com/radare/cydia/blob/master/packages/git/CONFIG the new pkg doesnt contains this issue. i just removed the 1.7.8 from the repo...

**Comment by Thireus** [comment]
Ok, I'm still getting the error. Did you push the update?

What's weird is that the package description from github doesn't match the one in the .deb package available in your repo.

**Comment by radare** [comment]
Yes the pkg should be fine now

**Comment by Thireus** [comment]
Still getting the error.

I'm not sure we are talking about the same package. I'm referring to the "git 2.11.0" package available in your repo: http://cydia.radare.org/debs/git_2.11.0_iphoneos-arm.deb

The package is listed on the repo as "git 2.11.0" via http://cydia.radare.org/debs/ (I don't know what you're referring to by "1.7.8" version)

Please see for yourself:

    wget http://cydia.radare.org/debs/git_2.11.0_iphoneos-arm.deb
    mkdir /tmp/out
    dpkg -e git_2.11.0_iphoneos-arm.deb /tmp/out
    grep Depends /tmp/out/control

As you can see, the output is:

    Depends: expat cacert

While it should be:

    Depends: expat, cacert

The comma is missing in the package "Depends" field of the control file. What is even weirder is that this line is completely different from the one that is here on this github repository. So either someone pushed a wrong .deb file by mistake in your repository or there is something fishy in your deployment process.

**Comment by radare** [comment]
OH damn! you are right :)

for some reason i put the DEPENDS in the makefile instead of the CONFIG file. pls try again :)

https://github.com/radare/cydia/commit/37dcc5abbf8c9be1235ed11545e72f98d86d9a86 <https://github.com/radare/cydia/commit/37dcc5abbf8c9be1235ed11545e72f98d86d9a86>

and happy new yeah

**Comment by Thireus** [comment]
No more warnings, issue is fixed! 👍

Thank you. :)
And happy new year to you as well!

**Comment by Thireus** [comment]
FYI, there are other issues now when installing the package.

![img_0007](https://cloud.githubusercontent.com/assets/721759/21579469/05b4855a-cfa9-11e6-8bbc-fe7b8f2ad074.jpg)

**Comment by radare** [comment]
uhm try again.. and happy new year ;)

**Comment by Thireus** [comment]
All good thanks. Happy new year!

**Comment by ada1016** [comment]
Steven6:~ root# git
-sh: /usr/bin/git: Bad CPU type in executable


any hint? please?

**Comment by ada1016** [comment]
By the way it is iOS 9.3.3 JB device

**Comment by radare** [comment]
32 or 64?

**Comment by ada1016** [comment]
64, thanks

**Comment by radare** [comment]
it should be good now
